---  
- hosts: all_pods
  connection: network_cli
  gather_facts: no
  ignore_errors: no
  strategy: free

  tasks:
  - name: RESET THE ROUTER TO BASELINE
    block:
      - name: COPY ROUTER BASELINE TO STARTUP
        ios_command:
          commands:            
            - command: 'config replace bootflash:netman/base/base.cfg force'
            - command: 'write mem'
    when: device == "RTR"

  - name: RESET THE SWITCH TO BASELINE
    block:
      - name: COPY SWITCH BASELINE TO STARTUP
        ios_command:
          commands:            
            - command: 'config replace flash:netman/base/base.cfg force'
            - command: 'write mem'
    when: device == "SW"

  - name: RESET THE MPLS TO BASELINE
    block:
      - name: COPY MPLS BASELINE TO STARTUP
        ios_command:
          commands:            
            - command: 'config replace flash:netman/base/base.cfg force'
            - command: 'write mem'
    when: device == "MPLS"
  
  - name: RELOAD THE DEVICE
    ios_command:
      commands:
        - command: "reload in 1\n"
          prompt: '[.*]'
          answer: "\r"



