---


  - hosts: all_pods
    connection: network_cli
    gather_facts: no 

    vars_prompt:
      - name: correct_config
        prompt: Please enter the correct PE number for comparison.... | PEx| i.e PE1 |
        private: no

    tasks:
      - name: diff running-config against master config THAT IS SAVED ON THE ANSIBLE VM
        ios_config:
          diff_against: intended
          intended_config: "{{ lookup('template', '{{ correct_config }}/{{ correct_config }}-{{ device }}-config.txt') }}"
 #         intended_config: "{{ lookup('template', 'enarsi_challenge_bugs/enarsi_challenge_bugs-{{ device }}-config.txt') }}"


      # USE diff_ignore_lines TO REMOVE ANY DIFFS YOU DONT WANT TO SEE FROM ANSIBLE OUTPUT    
          diff_ignore_lines:
            - parser config cache .*
            - alias .*
            - no diagnostic .*
            - diagnostic bootup level minimal
            - subsciber templating
            - multilink bundle-name
            - username .*
            - ip ssh version 2
            - no ip route-cache
            - license udi pid .*
            - mgcp behavior .*
            - mgcp profile .*
            - version .*
            - platform qfp utilization monitor .*
            - interface GigabitEtherenet0
            - interface GigabitEtherenet0/0
            - interface FastEthernet0


          backup: no
          backup_options:
#           filename: "{{ ('{{correct_config }}_{{ device }}.txt') }} "
            dir_path: "backup_diff/{{ location }}"  

