---
# IOS facts verifies that SSH is working correctly if not then the rescue block is activated.
# Rescue block send a Debug message and run the telnet module to enable SSH.
# When SSH is working correctly then rescuue block is bypassed.
     
- name: Verify SSH is enabled
  hosts: all_pods
  gather_facts: no
  serial: 8
  
  #ios_config: lines: hostname foo 
  #host: “{{ inventory_hostname }}”
  #username: cisco 
  #password: cisco 
  #authorize: yes 
  #auth_pass: cisco

  vars:
    
  tasks:
     - name: send configuration commands to IOS
       block:
         - name: Gather IOS Facts
           ios_facts:
             gather_subset: min

       rescue: 
         - name: SSH is Broken.
           debug: 
             msg: Enabling telnet and generating crypto keys on device {{ ansible_host }}     
       
         - telnet:
             user: cisco
             password: cisco
             login_prompt: "Username: "
             prompts:
                 - "[>|#]"
             command:
                 - terminal length 0
                 - configure terminal
                 - hostname {{ device }}
                 - ip domain-name ansiblemanaged.net
                 - crypto key gen rsa mod 1024
                 - ip ssh version 2
                 - line vty 0 4
                 - transport input all

     - name: Configure ansiblemanaged banner
       connection: network_cli
       ios_banner:
           banner: exec
           text: Managed by Ansible
           state: present              
...
